### ISSUE TITLE
bug in the recent update

### ISSUE THREAD

**Issue by mathjiajia** [monkoose/matchparen.nvim#12]
Got this error message:
`Error in packer_compiled: .../packer/start/matchparen.nvim/lua/matchparen/options.lua:32: bad argument #1 to 'pairs' (table expected
, got nil)
Please check your config for correctness`

Could you fix it?

ps: related configuration:
```lua
use {
        'monkoose/matchparen.nvim',
        config = [[require('matchparen').setup()]],
}
```

**Comment by monkoose** [comment]
On my way.

**Comment by monkoose** [comment]
Thank you for reporting. Should be fixed.

**Comment by mathjiajia** [comment]
Thanks. It has been fixed.

**Comment by ram02z** [comment]
Same issue again.

```
packer.nvim: Error running config for matchparen.nvim: .../packer/start/matchparen.nvim/lua/matchparen/options.lua:40: bad argument #1 to 'pairs' (table expected, got nil)
```

**Comment by monkoose** [comment]
@ram02z fixed. And thank you.
