### ISSUE TITLE
Error on terraform files

### ISSUE THREAD

**Issue by gegoune** [monkoose/matchparen.nvim#13]
While scrolling through terraform file I get following error:

```
Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: ...5efc2/share/nvim/runtime/lua/vim/treesitter/language.lua:25: no parser for 'terraform' language, see :help treesitter-parsers
stack traceback:
        [C]: in function 'error'
        ...5efc2/share/nvim/runtime/lua/vim/treesitter/language.lua:25: in function 'require_language'
        ...m/HEAD-a75efc2/share/nvim/runtime/lua/vim/treesitter.lua:39: in function '_create_parser'
        ...m/HEAD-a75efc2/share/nvim/runtime/lua/vim/treesitter.lua:94: in function 'get_parser'
        ...cker/start/matchparen.nvim/lua/matchparen/treesitter.lua:119: in function 'get_tree_root'
        ...cker/start/matchparen.nvim/lua/matchparen/treesitter.lua:191: in function 'skip_by_region'
        ...k/packer/start/matchparen.nvim/lua/matchparen/search.lua:162: in function 'match_pos'
        ...acker/start/matchparen.nvim/lua/matchparen/highlight.lua:99: in function 'update'
        ...ite/pack/packer/start/matchparen.nvim/lua/matchparen.lua:60: in function <...ite/pack/packer/start/matchparen.nvim/lua/matchparen.lua:60>
```

I do have `hcl` parser installed (there is no `terraform` parser).

matchparen.nvim version: 308dfede63b0e38aa6ad8a543217c611fd0e2b71
Neovim: NVIM v0.8.0-dev+1517-ga75efc237

**Comment by monkoose** [comment]
From first glance, not sure what can cause it from `matchparen` side. Let me check it futher.

This wasn't happen before last updates (like week ago)?

**Comment by gegoune** [comment]
Not sure, would have to bisect. Error goes away with matchparen.nvim disabled.

**Comment by monkoose** [comment]
What is the return of `:set filetype?`

Any example of the file you edit.

**Comment by gegoune** [comment]
`filetype=terraform`, I can trigger error by moving cursor over parenthesis on something like:

```hcl
resource "null_resource" {

}
```

**Comment by monkoose** [comment]
Should be fixed. Can you confirm it here?

**Comment by gegoune** [comment]
Fix confirmed, thank you very much, that was quick!

**Comment by monkoose** [comment]
Thank you for reporting such issue. Was not aware that some treesitter parsers behave like so.
