### ISSUE TITLE
Occasional error when I use LSP reformat the buffer.

### ISSUE THREAD

**Issue by raymond-w-ko** [monkoose/matchparen.nvim#14]
After reformatting a file with `vim.lsp.buf.format{async=true}` I get the error below. This occurs in Clojure file, if that matters. Then if I reformat again immediately, the error does not happen. But after a while, if I reformat, then the error occurs again.

```
Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: ...rko/nvim/share/nvim/runtime/lua/vim/treesitter/query.lua:422: bad argument #2 to 'handler' (string expected, got nil)
stack traceback:
        [C]: in function 'handler'
        ...rko/nvim/share/nvim/runtime/lua/vim/treesitter/query.lua:422: in function 'match_preds'
        ...rko/nvim/share/nvim/runtime/lua/vim/treesitter/query.lua:508: in function '(for generator)'
        ...cker/start/matchparen.nvim/lua/matchparen/treesitter.lua:45: in function 'cache_nodes'
        ...cker/start/matchparen.nvim/lua/matchparen/treesitter.lua:59: in function 'get_skip_node'
        ...cker/start/matchparen.nvim/lua/matchparen/treesitter.lua:158: in function 'skip_by_region'
        ...k/packer/start/matchparen.nvim/lua/matchparen/search.lua:162: in function 'match_pos'
        ...acker/start/matchparen.nvim/lua/matchparen/highlight.lua:108: in function 'update'
        ...ite/pack/packer/start/matchparen.nvim/lua/matchparen.lua:63: in function <...ite/pack/packer/start/matchparen.nvim/lua/matchparen.lua:63>
```

**Comment by monkoose** [comment]
Hello, for me it looks like upstream bug. For now i will `pcall` function that causes such issue, so it should work now. Can you test it and report? (It will just skip errors, so immediately after format brackets highlighting could be off).

**Comment by raymond-w-ko** [comment]
I just tested and it works fine.
1) format on already formatted document with cursor on a `(`. matchparen highlight still works.
2) format on a mis-indented document with cursor at start of line. I press `w` to advance to a `(`. matchparen highlight still works.

Thanks!
