### ISSUE TITLE
Option to change from highlighting pairs to underlining, etc

### ISSUE THREAD

**Issue by cloudk1d** [monkoose/matchparen.nvim#18]
Love the simplicity of this plugin! I would like, however, to be able to configure how matched characters are identified.

**Comment by monkoose** [comment]
Hello.
You are new to vim/neovim?

**Comment by cloudk1d** [comment]
> You are new to vim/neovim?

I've been using it for awhile, but am newly configuring it :)
Is this already available?

**Comment by monkoose** [comment]
Yes it is already available, with `hl_group` option. By default it is uses highlight group called `MatchParen`. You can check how it looks and its arguments with `:hi MatchParen`.  If you use some colorscheme that you installed as plugin (and my assumption you are, or else you would know how to change highlights), but you don't like how it's `MatchParen` highlight group looks you can check all the higlight groups with `:hi` command and find some underlined `xxx` and provide it's name to `hl_group` option:
```lua
require('matchparen').setup({
  hl_group = 'SomeHighlightName',
})

You can try `'Underlined'` first. If you didn't find any that met your requirements, you can change existing highlight group without changing colorscheme itself. But you should have at least basic scripting knowledge:

```lua
vim.api.nvim_create_autocmd({ 'VimEnter', 'ColorScheme' }, {
  callback = function() vim.api.nvim_set_hl(0, 'MatchParen', { underline = 1 }) end
})
```

I close this. If you still have questions about how neovim highlightings work ask them on appropriate resources, like reddit etc.

**Comment by monkoose** [comment]
Sorry, misunderstood your question at first read.

By underlining do you mean instead of `(foobar)` highlight `_` in `_foobar_`?
This is not possible and out of the scope of this plugin.
There is an option in neovim that this plugin uses internally `:h 'matchpairs'`, that you can change to add additional pairs, but as it is stated open and closing pair should be different characters.
