### ISSUE TITLE
Incorrect highlighting with inlay hints

### ISSUE THREAD

**Issue by Gaulm** [monkoose/matchparen.nvim#19]
When inlay hints are enabled the first hint next to the opening parentheses is highlighted as a matching parentheses.

**Comment by monkoose** [comment]
Thanks for reporting. Can you test how built-in matchparen plugin behaves?

The problem is, i'm not using hints myself (and not planning in a near future) and currently low on time to test it. So this would be postponed for some time.

PR's are welcome for sure.

**Comment by Gaulm** [comment]
Built-in matchparen behaves the same, the highlight is incorrect.

**Comment by Gaulm** [comment]
Fixed in neovim/neovim#24276

**Comment by monkoose** [comment]
Thanks. Good to know it. I actually was expecting that it would be fixed on neovim level.
