### ISSUE TITLE
Loop or previous error loading matchparen

### ISSUE THREAD

**Issue by zbirenbaum** [monkoose/matchparen.nvim#2]
I installed matchparen exactly as the readme states, however in the config file when I require('matchparen') neovim throws an error. I made sure to set:
`vim.g.loaded_matchparen = 1
`so I am at a bit of a loss as to what to do here.

I am on the latest neovim nightly/maybe a little ahead since I built from source from git.

Edit: Tried it from a standard nightly build from a few days ago I had installed but aliased. Still doesn't work :(

**Comment by zbirenbaum** [comment]
I'm dumb its 5am and I had a type in init.lua. Closing.

**Comment by monkoose** [comment]
I'm glad you that have fixed it fast.

Anyway i'm on some refactoring right now, that will further improve its speed in treesitter supported buffers, and then will improve README too, to make it more readable, with better English etc.
