### ISSUE TITLE
Attempt to compare number with nil.

### ISSUE THREAD

**Issue by rhcher** [monkoose/matchparen.nvim#7]
# example
test.py
``` python
print("{([(})])}")
```
# reproduce
1. open exists test.py file and when the cursor crosses you will see this error:
![image](https://user-images.githubusercontent.com/50723480/148416721-ad56f035-8d16-4342-9ddb-f577c0ecc920.png)
note that if you open a empty file and write those matching paren with delimitMate or some other plugins, then you delete some character to let those paren not matching, in that case you can't see this bug.
# misc
nvim version:NVIM v0.7.0-dev+839-g09d270bcea
matchparen.nvim conf: default
treesitter: installed python
This bug appears after lastest refactor so I guess you introduce some broken.

**Comment by monkoose** [comment]
Thank you. Seems like regression bug after latest update.
