### ISSUE TITLE
Issue when starting with multiple file arguments

### ISSUE THREAD

**Issue by jebaum** [monkoose/matchparen.nvim#8]
When starting up neovim with multiple arguments (and with `on_startup` set to true), e.g. `nvim file1 file2`, I get this error:

```
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua ....vim/bundle/matchparen.nvim/lua/matchparen/highlight.lua:59: attempt to index field 'matchpairs' (a nil value)
stack traceback:
        ....vim/bundle/matchparen.nvim/lua/matchparen/highlight.lua:59: in function 'update'
        [string ":lua"]:1: in main chunk
```

It seems like the `update()` function is getting executed before `conf.matchpairs` is defined. I've tried two fixes for this locally. One is to add a check for `matchpairs` existing before executing `update()`

```diff
diff --git i/lua/matchparen/highlight.lua w/lua/matchparen/highlight.lua
index abc6b7f..474deb1 100644
--- i/lua/matchparen/highlight.lua
+++ w/lua/matchparen/highlight.lua
@@ -33,6 +33,7 @@ end
 -- and then if there is matching brackets pair at the new cursor position highlight them
 function M.update(in_insert)
     M.remove()
+    if not conf.matchpairs then return end
 
     vim.g.matchparen_tick = vim.api.nvim_buf_get_changedtick(0)
     local line, col = utils.get_current_pos()
```

Since this plugin is so performance sensitive I'm a bit wary of adding any code to the update function, although checking if a key exists in a table should only take a fraction of a millisecond.

The other fix is a simple workaround of setting `on_startup` to false, and then calling `MatchParenEnable` on a `VimEnter` autocmd. I suppose this autocmd could conditionally be added in `create_autocmds()` if `on_startup` is true, which should also work. Not sure which approach you'd prefer so not opening a PR, but happy to do that if you want to go down any of those routes.

**Comment by monkoose** [comment]
Can't reproduce it. I think `VimEnter` autocmd doesn't invoke. The reason i suppose is because plugin required after this autocmd. 
Can you add something like `autocmd VimEnter * echom 'hello'` somewhere in the autocmds string? https://github.com/monkoose/matchparen.nvim/blob/bedea1c74f05b16515d58804f748fecc8b47a7e6/lua/matchparen.lua#L36-L41

Does it print 'hello' into cmdline?

If i remove this line i get the same error as you https://github.com/monkoose/matchparen.nvim/blob/bedea1c74f05b16515d58804f748fecc8b47a7e6/lua/matchparen.lua#L36

**Comment by jebaum** [comment]
Interesting, I wonder if the other autocmds in any particular configuration might have an impact. I'll debug with a minimal vimrc later today and try your suggestion as well

**Comment by monkoose** [comment]
Ok. I tested on some different PC with my old config that uses vim-plug instead of packer and it still works fine.

**Comment by monkoose** [comment]
So you haven't fixed this in your config?
Anyway on the second thought I think such kind of plugin should not break your neovim expirience if any error appears. I think it would be better to not highlight brackets at all, than constantly disrupt your editing with some error, that requires you to disable the plugin etc. So i will improve it behavior in a few days (already have some ideas how to do it).

**Comment by monkoose** [comment]
806d15a7d97f355b6cb8b58b74e3794c9ae64d2f should partly fix your issue.
